config system interface
 edit "port1"
  set alias "Outside"
  set ip 192.0.2.2 255.255.255.0
 next
 edit "port2"
  set ip 10.0.1.1 255.255.255.0
 next
end
config system zone
 edit "inside"
  set interface "port2"
 next
end
config firewall address
 edit "WEB1"
  set subnet 10.0.1.10 255.255.255.255
 next
end
config firewall addrgrp
 edit "WEB_SERVERS"
  set member "WEB1"
 next
end
config firewall service custom
 edit "HTTPS"
  set tcp-portrange 443
 next
end
config firewall policy
 edit 1
  set name "Allow-Web"
  set srcintf "outside"
  set dstintf "inside"
  set srcaddr "all"
  set dstaddr "WEB_SERVERS"
  set action accept
  set service "HTTPS"
  set nat enable
 next
end
config firewall vip
 edit "WEB-VIP"
  set extip 192.0.2.10
  set mappedip "10.0.1.10"
 next
end
config router static
 edit 1
  set dst 0.0.0.0 0.0.0.0
  set gateway 192.0.2.1
  set device "port1"
 next
end
